# reusable workflow triggered by other actions
name: CI

on:
  workflow_call:

jobs:
  terraform-checks:
    name: Terraform
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/terraform-checks.yaml@main
    with:
      charm-path: .
